#!/bin/bash
# https://stackoverflow.com/questions/18710992/how-to-add-album-art-with-ffmpeg

if [ -z "$1" ] || [ -z "$2" ]; then
	echo "ffmpeg-setcover [jpg] [mp3] ..."
	exit 1
fi

coverFilepath="$1"
shift

function runScript () {
	mp3Filepath="$1"

	if [ ! -f "$mp3Filepath" ]; then
		echo ""
		echoCommand "Skipped: $mp3Filepath"
		echo ""
		return
	fi

	tmpFilepath=`mktemp --dry-run /tmp/ffmpeg-setcover.XXXXXX.mp3`

	ffmpeg \
		-i "$mp3Filepath" \
		-i "$coverFilepath" \
		-map 0:0 \
		-map 1:0 \
		-codec copy \
		-id3v2_version 3 \
		-metadata:s:v title="Album cover" \
		-metadata:s:v comment="Cover (front)" \
		"$tmpFilepath"

	if [ $? -eq 0 ]; then
		mp3Dir=`dirname "${mp3Filepath}"`
		mp3Filename=`basename "${mp3Filepath}"`
		bakDir="${mp3Dir}/bak"
		mkdir -p "${bakDir}"
		bakFilepath="${bakDir}/${mp3Filename}.bak"
		mv "$mp3Filepath" "${bakFilepath}"
		cp "$tmpFilepath" "$mp3Filepath" # Move doesn't delete a temp file?
		rm "$tmpFilepath"
	else
		echo "[error] Could not set cover."
		rm "$tmpFilepath"
	fi
}

if [[ -p /dev/stdin ]]; then # Piped
	while read filepath; do
		if [ -z "$filepath" ]; then
			continue
		fi
		runScript "$filepath"
	done < /dev/stdin

else # Terminal
	for arg in "$@"; do
		runScript "$arg"
	done
fi
