#!/bin/bash

function echoCommand () {
    echo -e "$(tput setab 12) $(tput sgr0)$(tput setaf 12)\uE0B0$(tput sgr0)$(tput setaf 9) $@$(tput sgr0) "
}

echoCommand "journalctl -b 0 _COMM=plasmashell $@"
journalctl -b 0 _COMM=plasmashell $@
